name: AWS DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:        # <--- ADD THIS SECTION
      - 'README.md'
      - 'docs/**'

permissions:
  id-token: write   # This is REQUIRED for requesting the OIDC JWT
  contents: read    # Required for actions/checkout

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. SECURITY SCAN (The Gate)
      - name: Run Trivy (FS Scan)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
          severity: 'CRITICAL,HIGH'
          # We fail the build if vulnerabilities are found
          exit-code: '1'

      # 2. LOG IN TO AWS (The Handshake)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 3. BUILD AND PUSH (The Delivery)
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: security-demo-app # Must match what you created in AWS
          IMAGE_TAG: ${{ github.sha }}      # Uses the commit hash as a version tag
        run: |
          # Build the container
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          
          # Push it to AWS
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          # Also push 'latest' tag for convenience
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
